# Generated by Django 5.1.2 on 2024-10-24 09:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_user_video_remove_product_product_category_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_video',
            field=models.FileField(default=django.utils.timezone.now, upload_to='videos/'),
            preserve_default=False,
        ),
    ]
