# Generated by Django 5.1.2 on 2024-10-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_video_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_video',
            field=models.FileField(upload_to='video'),
        ),
    ]
