# Generated by Django 5.1.2 on 2024-10-24 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_video_video_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
